name: flutter_e_learning
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.4.3
  hooks_riverpod: ^2.4.3
  flutter_hooks: ^0.20.3
  dio: ^5.3.3
  intl: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.6.2

flutter:
  generate: true
  uses-material-design: true
